### ISSUE TITLE
Stored version of keys-manager contract

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-ecosystem/keys-manager#6]
- Stored version of keys-manager contract
- Add tests
- Add CI/CD (GitHub actions)

**Comment by zie1ony** [comment]
Keys description: https://docs.casperlabs.io/en/latest/implementation/accounts.html?highlight=keys#associated-keys-and-weights

1. Refactor it to use endpoints patter from erc20 and kv-storage: remove Api trait.
2. Remove delegate and undelegate.
3. Remove unused errors.
4. In tests, replicate JS code and do sth like:
```
 let session = SessionBuilder::new(session_code, session_args)
                .with_address(self.main_account)
                .with_authorization_keys(&[self.first_account, self.second_account])
                .build();
```
5. Update README like https://github.com/casper-ecosystem/auction-manager/
